In [1]:
print("Success")

Success


In [3]:
# importing numpy Library

import numpy as np

1. Create an Array
Create a NumPy array containing: 10, 20, 30, 40, 50

In [5]:
list = [10, 20, 30, 40, 50]

arr = np.array(list)

arr

array([10, 20, 30, 40, 50])

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


2. Find the following properties of the array:

Shape

Size

Number of dimensions

Data type

In [7]:
arr.shape

(5,)

In [9]:
arr.size

5

In [11]:
arr.ndim

1

In [12]:
arr.dtype

dtype('int64')

In [14]:
new_arr = np.array([[1,2,3,4],
                    [8,5,4,2],
                    [9,0,4,2]]
)

In [15]:
new_arr

array([[1, 2, 3, 4],
       [8, 5, 4, 2],
       [9, 0, 4, 2]])

In [16]:
print(np.shape(new_arr))

(3, 4)


In [18]:
print(np.size(new_arr))

12


In [19]:
print(np.ndim(new_arr))

2


In [20]:
print(new_arr.dtype)

int64


In [22]:
print(np.max(new_arr))

9


In [23]:
print(np.min(new_arr))

0


In [24]:
print(np.sum(new_arr))

44


In [25]:
np.mean(new_arr)

np.float64(3.6666666666666665)

In [26]:
np.median(new_arr)

np.float64(3.5)

In [27]:
np.std(new_arr)

np.float64(2.560381915956203)

In [28]:
len(np.unique(new_arr))

8

In [29]:
new_arr

array([[1, 2, 3, 4],
       [8, 5, 4, 2],
       [9, 0, 4, 2]])

In [30]:
np.sum(new_arr, axis=0)

array([18,  7, 11,  8])

In [31]:
np.sum(new_arr, axis=1)

array([10, 19, 15])

In [32]:
np.mean(new_arr, axis=0)

array([6.        , 2.33333333, 3.66666667, 2.66666667])

In [33]:
np.mean(new_arr, axis=1)

array([2.5 , 4.75, 3.75])

In [ ]:
(np.max(new_arr))

np.int64(9)

In [35]:
new_arr.nbytes

96

In [36]:
np.argmax(new_arr)

np.int64(8)

In [39]:
np.unravel_index(np.argmax(new_arr), new_arr.shape)

(np.int64(2), np.int64(0))

In [37]:
np.argmin(new_arr)

np.int64(9)

In [40]:
np.unravel_index(np.argmin(new_arr), new_arr.shape)

(np.int64(2), np.int64(1))

3. Create a NumPy array containing numbers from 1 to 20.

In [41]:
arr = np.arange(1,21)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
type(arr)

numpy.ndarray

4. Even Numbers

Create a NumPy array containing all even numbers from 10 to 100.

In [44]:
arr = np.arange(1,101,2)

In [45]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

5. Odd Numbers

Create a NumPy array containing all odd numbers from 1 to 50.

In [46]:
arr = np.arange(2,51, 2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [47]:
print(type(arr))

<class 'numpy.ndarray'>


6. First Element

Given:

arr = np.array([10, 20, 30, 40, 50])

Find the first element.

In [48]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])

10


7. Last Element

Using the same array, find the last element.

In [49]:
print(arr[len(arr)-1])

50


In [62]:
arr[len(arr)-1]

np.int64(50)

8. First Three Elements

Extract the first three elements from the array.

In [50]:
for i in range(0,3):
    print(arr[i])

10
20
30


In [60]:
arr[0:3]

array([10, 20, 30])

9. Last Two Elements

Extract the last two elements from the array.

In [51]:
for i in range(len(arr)-1, len(arr)-3, -1):
    print(arr[i])

50
40


In [59]:
arr[len(arr)-2:len(arr)]

array([40, 50])

10. Reverse an Array

Reverse the following array:

arr = np.array([10, 20, 30, 40, 50])

In [52]:
arr

array([10, 20, 30, 40, 50])

In [55]:
np.flip(arr)

array([50, 40, 30, 20, 10])

In [56]:
arr

array([10, 20, 30, 40, 50])

In [57]:
arr[::-1]

array([50, 40, 30, 20, 10])

11. Addition

Add 10 to every element:

arr = np.array([5, 10, 15, 20, 25])

In [63]:
arr

array([10, 20, 30, 40, 50])

In [64]:
arr + 10

array([20, 30, 40, 50, 60])

12. Multiplication

Multiply every element by 2.

In [65]:
arr

array([10, 20, 30, 40, 50])

In [66]:
arr * 2

array([ 20,  40,  60,  80, 100])

13. Square of Elements

Find the square of every element in the array.

In [67]:
arr

array([10, 20, 30, 40, 50])

In [68]:
arr * 0.5

array([ 5., 10., 15., 20., 25.])

In [69]:
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [70]:
arr

array([10, 20, 30, 40, 50])

14. Maximum and Minimum

Find the maximum and minimum values in an array.

In [71]:
np.max(arr)

np.int64(50)

In [72]:
np.min(arr)

np.int64(10)

15. Index of Maximum

Find the index of the maximum value in an array.

In [73]:
np.argmax(arr)

np.int64(4)

In [74]:
np.argmin(arr)

np.int64(0)

🟡 Level 2 — Filtering & Mathematical Operations

Use the following sales data:

sales = np.array([12000, 25000, 18000, 45000, 32000, 15000, 50000])