Add elements

In [1]:
import numpy as np

a = np.array([1,2,3,4])

np.append(a,90)

array([ 1,  2,  3,  4, 90])

In [ ]:
a = np.array([[1,2],[3,4]]) # 2d array convert into 1d arrey the append aperation perform

np.append(a, 400)

array([  1,   2,   3,   4, 400])

In [5]:
np.append(a, [400, 100, 50])

array([  1,   2,   3,   4, 400, 100,  50])

insert

In [14]:
np.insert(a, [1], [20,50], axis=1) # array index value

array([[ 1, 20, 50,  2],
       [ 3, 20, 50,  4]])

Delete

In [24]:
print(a)
np.delete(a,0,axis=0)  # convert arrey into 1d then delete index

# axis=0  -> delete the row

[[1 2]
 [3 4]]


array([[3, 4]])

In [23]:
print(a)
np.delete(a,0,axis=1) 

# axis=1  -> delete the column

[[1 2]
 [3 4]]


array([[2],
       [4]])