In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
zero = np.zeros(5)
print(zero)

z1 = np.zeros((3,3))
print(z1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
on = np.ones((2,2))
print(on)

[[1. 1.]
 [1. 1.]]


In [6]:
n = np.empty(5)
print(n)

[0. 0. 0. 0. 0.]


In [7]:
arr = np.full((2,3),8)
print(arr)

[[8 8 8]
 [8 8 8]]


In [8]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [9]:
print(np.arange(1,20,2))


[ 1  3  5  7  9 11 13 15 17 19]


In [12]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
print(np.logspace(0,2,5))

[  1.           3.16227766  10.          31.6227766  100.        ]


In [14]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
print(np.diag([1,5,9]))

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [17]:
print(np.random.rand(2,3))

[[0.64237538 0.58568827 0.72506401]
 [0.47762786 0.95827054 0.89512423]]


In [19]:
print(np.random.randint(1,10, size=(2,4)))

[[3 1 4 8]
 [6 3 6 6]]


In [20]:
print(np.random.randn(2,3))

[[-0.14925442 -0.48613101 -1.72030879]
 [ 1.24644745 -1.44055103 -0.24102895]]


In [21]:
print(np.random.choice([8,9,4,2], size=(2,4)))

[[8 4 9 2]
 [2 9 2 9]]
