Aggrating fn

In [1]:
import numpy as np

l = [7,8,2,4,9,6,4,1]

arr = np.array(l)
print(arr)

[7 8 2 4 9 6 4 1]


In [2]:
print(np.sum(arr))

41


In [3]:
print(np.min(arr))
print(np.max(arr))
print(np.size(arr))

1
9
8


In [4]:
print(np.mean(arr))

5.125


In [5]:
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 7 15 17 21 30 36 40 41]
[    7    56   112   448  4032 24192 96768 96768]


In [6]:
a = [100, 150, 199, 200, 250, 130]
b = [10, 50, 30, 40, 30, 10]

price = np.array(a)
quantity = np.array(b)

print(price)
print(quantity)

[100 150 199 200 250 130]
[10 50 30 40 30 10]


In [7]:
c = np.cumprod([price, quantity], axis=0)
print(c)

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]


In [8]:
print(c[1].sum())

31270


statical function

In [9]:
l = [7,8,2,4,9,6,4,1]

arr = np.array(l)

print(arr)

[7 8 2 4 9 6 4 1]


In [13]:
import statistics as state

print(state.mode(arr))

4


In [14]:
print(np.std(arr))

2.666341125962693


In [15]:
print(np.var(arr))

7.109375


In [18]:
a = [100, 150, 199, 200, 250, 130]
b = [10, 50, 30, 40, 30, 10]

price = np.array(a)
quantity = np.array(b)

print(np.corrcoef([price, quantity]))  # shows how 2 arrays are relate with each other


"""
-1 = Inversaly proportional
0 = No relation
1 = Proportional
"""


[[1.         0.48161196]
 [0.48161196 1.        ]]


'\n-1 = Inversaly proportional\n0 = No relation\n1 = Proportional\n'