Join

In [10]:
# join 2 arrey -> concatenate

import numpy as np

arr1 = np.array([[1,2],
                 [3,5]])

arr2 = np.array([[4,5],
                 [6,9]])

print(arr1)
print(arr2)

print(np.concatenate([arr1, arr2]))

[[1 2]
 [3 5]]
[[4 5]
 [6 9]]
[[1 2]
 [3 5]
 [4 5]
 [6 9]]


In [11]:
print(np.concatenate([arr1, arr2], axis=1))

[[1 2 4 5]
 [3 5 6 9]]


In [12]:
print(np.hstack([arr1, arr2]))

[[1 2 4 5]
 [3 5 6 9]]


In [13]:
print(np.vstack([arr1, arr2]))

[[1 2]
 [3 5]
 [4 5]
 [6 9]]


Split arrey


In [14]:
a = np.array([20,40,30,40,10,20])
print(a)

[20 40 30 40 10 20]


In [17]:
b = (np.array_split(a,3))
print(b)
# return a list of the spilited arreys

[array([20, 40]), array([30, 40]), array([10, 20])]


In [18]:
print(b[0])

[20 40]


In [19]:
a = np.array([[20,40,30],[40,10,20]])
print(a)

[[20 40 30]
 [40 10 20]]


In [24]:
b = np.array_split(a,2)

In [26]:
print(b)
print(b[0])

[array([[20, 40, 30]]), array([[40, 10, 20]])]
[[20 40 30]]
