Create a NumPy array containing:
[10, 20, 30, 40, 50]

In [1]:
import numpy as np

In [2]:
l = [10, 20, 30, 40, 50]

arr = np.array(l)
print(arr)

[10 20 30 40 50]


Create an array of numbers from 1 to 20.


In [3]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Create an array of even numbers from 2 to 50.

In [4]:
arr = np.arange(2,51,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


Create an array of 10 zeros.

In [5]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create an array of 15 ones.

In [6]:
arr = np.ones(15)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Create an array:
[5, 5, 5, 5, 5, 5]
without typing 5 six times.

In [8]:
arr = np.full(6,5)
print(arr)

[5 5 5 5 5 5]


Given:

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [9]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [10]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
"""
Print:
shape
size
ndim
dtype
"""

print(arr, "\n")
print(np.shape(arr), "\n")
print(np.size(arr), "\n")
print(np.ndim(arr), "\n")
print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

(3, 3) 

9 

2 

int64


Find total number of elements.

In [15]:
print("Total number of elements : ", np.size(arr))

Total number of elements :  9


Find number of rows and columns.

In [17]:
print("Rows : ")
print(arr.shape[0])
print("colum : ")
print(arr.shape[1])

Rows : 
3
colum : 
3


arr = np.array([10,20,30,40,50,60,70,80])

Print:
30


In [18]:
arr = np.array([10,20,30,40,50,60,70,80])

In [19]:
print(arr)

[10 20 30 40 50 60 70 80]


In [20]:
print(arr[2])

30


Print:
[20,30,40]

In [21]:
print(arr[1:4])

[20 30 40]


Print last 3 elements.

In [22]:
print(arr[-3:])

[60 70 80]


Reverse the array using slicing.

In [23]:
print(arr[::-1])

[80 70 60 50 40 30 20 10]


Given:

a = np.array([1,2,3,4,5])

b = np.array([10,20,30,40,50])

Add both arrays.

In [24]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

In [25]:
print(a + b)

[11 22 33 44 55]


In [26]:
print(np.add(a,b))

[11 22 33 44 55]


Subtract both arrays.

In [27]:
print(a-b)
print(np.subtract(a,b))

[ -9 -18 -27 -36 -45]
[ -9 -18 -27 -36 -45]


Multiply both arrays.


In [28]:
print(a*b)
print(np.multiply(a,b))

[ 10  40  90 160 250]
[ 10  40  90 160 250]


Divide b by a.

In [29]:
print(b/a)

[10. 10. 10. 10. 10.]


In [30]:
print(np.divide(b,a))

[10. 10. 10. 10. 10.]


Square every element of a.

In [32]:
print(np.pow(a, 2))

[ 1  4  9 16 25]


Find cube of every element of a.


In [33]:
print(np.pow(a,3))

[  1   8  27  64 125]


Given:
arr = np.array([5,10,15,20,25])

In [34]:
arr = np.array([5,10,15,20,25])

In [35]:
"""
Find:
sum
mean
max
min
"""

print(arr)

[ 5 10 15 20 25]


In [36]:
print(np.sum(arr))

75


In [37]:
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

15.0
25
5


Find median.

In [38]:
print(np.median(arr))

15.0


Find standard deviation.

In [39]:
print(np.std(arr))

7.0710678118654755


Find index of maximum element.

In [42]:
print(np.where(arr == np.max(arr)))

(array([4]),)


Find index of minimum element.


In [43]:
print(np.where(arr == np.min(arr)))

(array([0]),)


Create:

[[1 2 3]

 [4 5 6]

 [7 8 9]]

In [44]:
arr = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

In [45]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Print second row.


In [47]:
print(arr[1])

[4 5 6]


Print third column.


In [51]:
print(arr[:,2])

[3 6 9]


Print:
5

In [52]:
print(arr[1][1])

5


Print:

[[1 2]

 [4 5]]


In [55]:
# arr[row_start:row_end, col_start:col_end]

print(arr[0:2,0:2])

[[1 2]
 [4 5]]


Find sum of each row.


In [57]:
print(np.sum(arr[0]))
print(np.sum(arr[1]))
print(np.sum(arr[2]))

6
15
24


Reshape

In [58]:
l = [1,2,3,4,5,6,7,8,9,10,11,12]
# Convert it into:
# 3 × 4
arr = np.array(l)
print(l)
print(np.shape(arr))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
(12,)


In [60]:
print(np.reshape(arr, (3,4)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Convert same array into:
2 × 6

In [61]:
print(np.reshape(arr, (2,6)))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [63]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr)
print("\n\n")
print(np.reshape(arr, (np.size(arr))))

[[1 2 3]
 [4 5 6]]



[1 2 3 4 5 6]


Boolean Masking

In [64]:
arr = np.array([12,45,7,89,34,22,100])

Print all elements greater than 30.

In [65]:
fa = arr > 30
newarr = arr[fa]
print(newarr)

[ 45  89  34 100]


Print all even numbers.

In [66]:
fa = arr % 2 == 0
newarr = arr[fa]
print(newarr)

[ 12  34  22 100]


Count how many numbers are greater than 50.


In [67]:
fa = arr > 50
mewarr = arr[fa]
print(np.size(newarr))

4


Replace all numbers less than 20 with 0.


In [68]:
fa = arr < 20
arr[fa] = 0

print(arr)

[  0  45   0  89  34  22 100]


Find second largest number in a NumPy array.

In [69]:
arr = np.array([12,45,7,89,34,22,100])

In [70]:
arr = np.sort(arr)
print(arr)

[  7  12  22  34  45  89 100]


In [71]:
print(arr[-2])

89


Remove duplicate values from:
[1,2,2,3,4,4,5,6,6]


In [72]:
l = [1,2,2,3,4,4,5,6,6]

arr = np.array(l)

In [73]:
print(arr)

[1 2 2 3 4 4 5 6 6]


In [74]:
print(np.unique(arr))

[1 2 3 4 5 6]


Check whether an array contains a particular number entered by user.

In [75]:
arr = np.array([8,9,4,5,6,1,7,8,70,22,18])

el = int(input("Enter the number for search : "))

if el in arr:
    print(True)
else:
    print(False)

True


In [77]:
print(el in arr) # sort method

True


Count frequency of each element.


In [79]:
arr = np.array([8,9,4,5,6,1,7,8,70,22,18])

print(np.count_nonzero(arr == 8))

2


In [80]:
print(np.count_nonzero(arr == 2))

0


Find all prime numbers between 1 and 100 using NumPy.


In [81]:
arr = np.arange(1,101)

for i in arr:
    if i < 2:
        continue
    
    isPrime = True
    
    for j in range(2, i):
        if i % j == 0:
            isPrime = False
            break
    
    if isPrime:
        print(i, end=" ")

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 