Sort

In [1]:
import numpy as np

arr = np.array([8,7,6,1,74,8,6])

print(np.sort(arr))

[ 1  6  6  7  8  8 74]


In [3]:
print(np.sort(arr)[::-1])

[74  8  8  7  6  6  1]


Search

In [4]:
arr = np.array([8,7,6,1,74,8,6])

In [ ]:
s = np.where(arr == 99)  # return index of the values
print(s)

s = np.where(arr == 74)
print(s)

(array([], dtype=int64),)
(array([4]),)


In [ ]:
s = np.where(arr > 5)  # return index of the values
print(s)

(array([0, 1, 2, 4, 5, 6]),)


In [ ]:
s = np.where(arr%2 == 0)  # return index of the values
print(s)

(array([0, 2, 4, 5, 6]),)


in sorted arrey

In [13]:
print(arr)

[ 8  7  6  1 74  8  6]


In [16]:
s = np.sort(arr)  # first sort arrey then search 
print(s)

[ 1  6  6  7  8  8 74]


In [15]:
np.searchsorted(s, 7)

np.int64(3)

Filter

In [17]:
arr = np.array([8,9,7,2,5])
print(arr)

[8 9 7 2 5]


In [19]:
fa = [True,False,True,False,False]

new = arr[fa]
print(new)

[8 7]


In [20]:
print(arr)

[8 9 7 2 5]


In [21]:
fa = arr % 2 == 0
new = arr[fa]
print(new)

[8 2]
